### ISSUE TITLE
Possibly not possible to catch errors during construction

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#2181]

**Comment by rjharmon** [comment]
I'm not set up for dev in pouchdb repo; this was a test application for trialling pouchdb as a persistence layer for a backbone app. Perhaps an instance of the application was open in another tab during the destroy operation.

**Comment by ThomasAnonymous** [comment]
I've just experienced the same effect, new install of 3.3.1 on Chromium. After refactoring existing code to use PouchDB and running some inserts I added a db.destroy(); and got a lot of unhandled promise rejections while the db was closing (expected and fine) but on a refresh I got the same error as above:
Uncaught NotFoundError: Failed to execute 'objectStore' on 'IDBTransaction': The specified object store was not found
Chromium indicated that the IndexedDB was still present, but there were no indexes or stores displayed. No joy from PouchDB.destroy either. I deleted the IndexedDB but the error remained. After deleting all local data (I believe Local Storage was the only thing left) it is working fine and I can't replicate the error. I'll keep trying at it for a bit and see if I can some up with something more helpful.

**Comment by nolanlawson** [comment]
Please do provide a reproducible test case if you can. In the meantime, I'd recommend just not using `destroy()` unless you have to.

This issue seems related to https://github.com/pouchdb/pouchdb/issues/3539 and https://github.com/pouchdb/pouchdb/issues/3415 and may be Chrome-only.

**Comment by tomsun** [comment]
I too run into this behavior, while using destroy() on each page load to reset a test database before re-use. On the n:th page reload (where it is not clear to me at this point what makes n unique) and every time thereafter, `new PouchDB('foo')` throws the error mentioned.

"Uncaught NotFoundError: Failed to execute 'objectStore' on 'IDBTransaction': The specified object store was not found."
IndexedDB, Chromium 37.0.2062.120,

**Comment by nolanlawson** [comment]
My advice to people is to never use `destroy()`. It seems very unstable in IndexedDB.

**Comment by svnlto** [comment]
I've just gotten that error removing indexedb via `chrome://settings/cookies`  ¯\_(ツ)_/¯

**Comment by mrzor** [comment]
After corrupting my database, I attempted to `destroy()` it, unaware of Nolan's advice that I subsequently discovered.

I experienced the same "Uncaught NotFoundError: Failed to execute 'objectStore' on 'IDBTransaction': The specified object store was not found." as reported by others in the thread.

I was able to finish the removal of the database using `indexedDB.deleteDatabase('_pouch_DBNAME')`.

There is a helpful [Stack Overflow comment](http://stackoverflow.com/questions/9384128/how-to-delete-indexeddb-in-chrome/15046024#15046024) about opened databases that may be relevant.

**Comment by nolanlawson** [comment]
You shouldn't need to explicitly call `indexedDB.deleteDatabase` anywhere. We do that under the hood, and we do it in a very subtle way to avoid bugs in IE. So even if your fix works in Chrome, you may find it suddenly breaking in IE.

That being said, another workaround that I've found for this particular Chrome bug is this: if you have map/reduce indexes, just query each one until they're complete, and do that before destroying:

```js
// force the index to get built
db.query('myddoc/myview', {limit: 0}).then(function () {
  // then destroy after the index is built
  return db.destroy();
});
```

**Comment by daleharvey** [comment]
Old bug, should be fixed

**Comment by urbgimtam** [comment]
I'm using PouchDB 4.0.0, and it still happens if you call db.destroy() too many times (or while it's performing some task). It's definitely not fixed.

**Comment by Ampakinetic** [comment]
I just had it occur to me as well, using PouchDB 4.0.3 - wanted to start afresh so called db.destroy from the console - now getting for subsequent requests in Chrome 45.0.2454.101 m: 
```
Uncaught NotFoundError: Failed to execute 'objectStore' on 'IDBTransaction': The specified object store was not found.d @ VM6600 s.js:2t @ VM6600 s.js:2a.8.W.onupgradeneeded @ VM6600 s.js:2
VM6600 s.js:2 

Failed to open indexedDB, are you in private browsing mode?
```
It was working fine up until the destroy.

**Comment by nolanlawson** [comment]
TBQH when I'm testing PouchDB, I often run into bugs (in every browser I test - Chrome, Firefox, IE) where the browser gets into an unrecoverable state and refuses to open IndexedDB. In those cases, I just clear away the data and start fresh. @Ampakinetic it sounds like that's what you ran into. :/

**Comment by Ampakinetic** [comment]
Thanks, agree this fixed it for me too. I guess I was worried it could
happen during normal use as I intend to remove the database when the user
logs out. Also thank you so much for the work you're doing and providing
great support for pouchdb users. It's an amazing tool that enables a lot of
things.

**Comment by nolanlawson** [comment]
Sadly I think it is a possibility if you ever use `destroy()`, which is more a bug with browser implementations of IndexedDB than anything. If you could find a way to consistently reproduce, it would make for a great bug report on Chrome.

**Comment by rjharmon** [comment]
I'm thinking this can probably be reproduced similarly to a memory-leak: create multiple clients, one of which prevents the localStorage deletion (in the other client) from being actually executed all the way to completion.  

One possible workaround might be to store a deletion flag prior to deleting localStorage, so that the initialization sequence can observe that flag and complete the initiated-but-blocked deletion at a time when it's more likely to succeed.

**Comment by stuartpb** [comment]
I just ran into this on my Chromebook. Could it maybe have something to do with refreshing the page before the database is finished deleting, causing the deletion operation to be inadvertently cancelled?

**Comment by nolanlawson** [comment]
@stuartpb One of the issues is that `destroy()` is not transactional in IDB - it's a separate operation, `destroyDatabase`. We have enough issues with that implementation cross-browser (very buggy, especially on IE) that we will probably move to a "soft destroy" in later versions (i.e. just clear the object stores in a transaction).
