### ISSUE TITLE
Duplicate attachments for doc update (& putAttachment)

### ISSUE THREAD

**Issue by natcohen** [pouchdb/pouchdb#3234]
Hello,

CouchDB has implemented a way not to duplicate existing attachments when we update a doc (https://issues.apache.org/jira/browse/COUCHDB-62). By using pouch.put() it duplicates these attachments and therefore exponentially increases DB size!

A way to verify that is to create a doc with a string value and a big attachment. Update the string and you'll see your couchdb will double in size.

BTW, adding an additional attachment should not duplicate existing ones either...

Thanks

**Comment by natcohen** [comment]
Any plan to fix this old issue? I've tried with the latest version (5.4.5) and the problem persists!

**Comment by nolanlawson** [comment]
Sorry, this fell under the radar. It does seem to be a bug and there do seem to be steps to reproduce.

**Comment by nolanlawson** [comment]
Upgrading from enhancement to bug because it sounds like our replicator isn't properly collapsing attachments when replicating to Couch, which as noted in https://github.com/pouchdb/pouchdb/issues/3234#issuecomment-68017309 can cause some pretty severe excess disk usage.

**Comment by doppler** [comment]
I'm seeing this same behavior. The browser-based app I'm building is for managing collections of videos and photos, and each time I update a doc with attached videos in PouchDB and I have syncing to CouchDB enabled, the CouchDB database increases in size proportionate to the size of the PouchDB attachments. Additionally, my app hangs until the replication is complete. If I disable syncing and update the same doc with multiple existing video attachments, there is no hanging and no delay.

I'll probably be changing this to an Electron app and using the filesystem to store videos, but I'd love to see this issue resolved, because it leaves more options open :-)

**Comment by natcohen** [comment]
@nolanlawson any chance this will get fixed for v7?

**Comment by nolanlawson** [comment]
This fell under the radar. If you could provide a test case to reproduce (jsbin or even a node script), that would help out enormously because it would save us a lot of time. :)

**Comment by hahnah** [comment]
@nolanlawson I've tried with PouchDB 6.3.4 and the problem still persists.

This can cause severe disk & network capacity.
In my situation, I added a short string entry to each 250 documents (every documents has an attachment of 1MB image file). Then push-replication increased DB size by 250MB and took 25 minutes.  

I hope scripts blow help you test https://github.com/pouchdb/pouchdb/issues/3234#issuecomment-68017309.

```
#!/bin/sh

curl -X PUT http://admin:password@XXX.XXX.XXX.XXX:5984/mydb
curl -vX PUT http://admin:password@XXX.XXX.XXX.XXX:5984/mydb/mydoc/image10mb.jpg --data-binary @image_10mb.jpg -H "Content-Type:image/jpeg"
```

```
<!DOCTYPE html>
<html>
<head>
	<script src='pouchdb-6.3.4.min.js'></script>
</head>
<body>
	<script type="text/javascript">
		localDB = new PouchDB('localDB')
		remoteDB = new PouchDB('http://admin:password@XXX.XXX.XXX.XXX:5984/mydb')
		
		localDB.replicate.from(remoteDB).on('complete', function (response) {
			console.log('pulled', response)
			localDB.get('mydoc').then(function(doc){
				doc.name = 'John';
				return localDB.put(doc)
			}).then(function(result){
				console.log('modified', result)
				localDB.replicate.to(remoteDB).on('complete', function (response) {
					console.log('pushed', response)
				})
			})
		})
	</script>
</body>
</html>
```

**Comment by natcohen** [comment]
@nolanlawson This bug should not be closed...

**Comment by natcohen** [comment]
@nolanlawson This bug should not be closed...

**Comment by natcohen** [comment]
@daleharvey Sorry to ask you since you're not in the thread but I see that you are active. Could you please re-open this issue? I don't think it has been fixed and it is a major issue.

**Comment by craftzdog** [comment]
It still happens on PouchDB@8.0.1

**Comment by slothtopus** [comment]
This is also still happening with PouchDB v9.0.0. Replicating a simple text change in a document with a large attachment appears to duplicate the attachment in the db (based on size). If live sync is on, the db can easily explode in size if attachments are used.
