### ISSUE TITLE
High CPU usage if db.changes({live:true}) called more than once

### ISSUE THREAD

**Issue by mgjv** [pouchdb/pouchdb#3632]
I stumbled on this when I accidentally included the same javascript twice. The following will result in high CPU usage

var db = new PouchDB('tester')
db.changes({ since: 'now', live: true })
db.changes({ since: 'now', live: true })

environment: Google Chrome Version 41.0.2272.76 (64-bit) on Mac OS X 10.10.2
out of 8 cores, 4 run up to 50%

**Comment by mgjv** [comment]
Problem also occurs with Firefox16.0.1 and Safari 8.04 (10600.4.10.7) on Mac OS X

Problem does NOT occur on Firefox Developer Edition 38.0a2

**Comment by oliverdm** [comment]
Similar problem with high CPU and disk utilization (> 80%) when using live sync and live changes in Internet Explorer 11 simultaneously.

Resource utilization stays high up to several minutes, goes down at some point, but also goes up again with new changes. Also happens with an empty database.

The following HTML should reproduce the issue when running on a localhost with CouchDB:

```
<!DOCTYPE html>
<html>
<head>
    <title>HIGH CPU AND DISK UTILIZATION IN IE 11</title>
    <script src="path/to/pouchdb.js"></script>
</head>
<body>
<script>
var localDb = new PouchDB("test");
var remoteDb = new PouchDB("http://localhost:5984/test");

var syncLive = PouchDB.sync(localDb, remoteDb, {
    live: true
});
var changesLive = localDb.changes({
    live: true,
    since: 'now'
});
</script>
</body>
</html>
```

According to IE profiler hot spots are:
 - Anonymous function in pouchdb.js line 8441
 - EventEmitter.prototype.emit in pouchdb.js 9118

(PouchDB version 3.3.1)

**Comment by 6f** [comment]
I ran into the same issue, but I think I fixed mine with the following commit:
6f/pouchdb@123d41b89a6b6b3d499102119fb75a3d6f5205ca

I'd appreciate if you could test if the patch solves the issue that you're having.

**Comment by mgjv** [comment]
Well found.

I checked out branch 3632-issue-non-deterministic-loop which contains the above commit, and can confirm that the problem no longer occurs. It still occurs on master.

tested on Chrome, Firefox and Safari, as in initial report/

**Comment by nolanlawson** [comment]
@6f could you open up a PR? I'd be happy to approve the fix, assuming it passes the tests. Seems like a good find to me.

**Comment by nolanlawson** [comment]
Actually that commit as some small issues; I've added comments to it.

Could someone please provide a live reproducible test case? @oliverdm your sample doesn't demo the issue for me, because I don't have your "test" database in my CouchDB. ;)

**Comment by 6f** [comment]
I can reproduce the bug consistently in chromium using the following testcase:
```html
<!doctype html>                                                                                                                                 
<title>PouchDB issue #3602</title>                                                                                                              
<script type="text/javascript" src="https://github.com/pouchdb/pouchdb/releases/download/3.3.1/pouchdb-3.3.1.min.js"></script>                  
<script type="text/javascript">                                                                                                                 
var testDb = new PouchDB("bug3602");                                                                                                      
                                                                                                             
for(var i=1; i<10; ++i) {                                                                                                                       
  testDb.changes({live:true}).on("change", function(change) {                                                                                   
    console.log('listener' + i + ' got a change event');                                                                                        
  });                                                                                                                                           
}

setTimeout(function() {                                                                                                                         
  testDb.put({'_id': ''+new Date().getTime(), 'msg': 'Hello PouchDB'});                                                                         
}, 200);                                                                                                                                        
</script>                                                                                                                                       
```

**Comment by rague** [comment]
I have the same problem using live sync and live changes, with pouchdb 3.5... Did you find a solution ?

**Comment by nolanlawson** [comment]
@rague Can you try 3.6.0, which was released yesterday?

**Comment by rague** [comment]
Cool ! It works with 3.6.0 ! Thank you.

**Comment by 6f** [comment]
I think the bug is still present. I still can consistently reproduce the bug in chromium with the testcase I posted previously. Here's the testcase updated to use version 3.6.0:
```html
<!doctype html>
<title>PouchDB issue #3632</title>
<script type="text/javascript" src="https://github.com/pouchdb/pouchdb/releases/download/3.6.0/pouchdb-3.6.0.min.js"></script>
<script type="text/javascript">                                                                                                                 
var testDb = new PouchDB("bug3602");                                                                                                      

for(var i=1; i<10; ++i) {
  (function(i) {                                                                                                                       
    testDb.changes({live:true}).on("change", function(change) {                                                                                   
      console.log('listener' + i + ' got a change event');                                                                                        
    });
  })(i);
}

setTimeout(function() {                                                                                                                         
  testDb.put({'_id': ''+new Date().getTime(), 'msg': 'Hello PouchDB'});                                                                         
}, 200);                                                                                                                                        
</script>
```

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/52225348190e89b20e9a10109bf2fc56ee753728
