### ISSUE TITLE
db.put(doc) silently failing (chrome extension)

### ISSUE THREAD

**Issue by RichardLitt** [pouchdb/pouchdb#3719]
I've got a very simple `db.get(doc)` with a `db.put(doc)` inside of it, but the db.put is returning neither a response nor a value. I'm not sure how to diagnose this problem. I tried switching from callbacks to promises to diagnose it (grasping at straws here), which explains the random comments. Any ideas? 

Here's my code: 

```js
function saveSelection (documentId, selection) {
  console.log('Inside saveSelection')

  db.get(documentId).then(function (value) {
    // if (err && err.name !== 'not_found') {
    //   return console.log('Failed to get ' + documentId + 'from db', err)
    // }

    /* Instantiate the object if it doesn't exist yet */
    value = value || {}
    value._id = documentId

    /* Add in the selection to the selections array */
    value.selections = value.selections || []
    value.selections.push(selection)

    /* Get rid of prototypes so we can put this to the database */
    value = JSON.parse(JSON.stringify(value))

    // console.log('value', value)
    return db.put(value)
  }).then(function (response) {
    console.log('response', response)

    // if (err) { console.log('Failed to save selection', err) }
    // console.log('Stored ' + response.id + ' away...', response)

  }).catch(function (err) {
    console.log(err)
  })
}
```

**Comment by nolanlawson** [comment]
This code looks correct to me; I have no idea why it would neither print a response nor an error. Can you provide a live test to reproduce? That would be very helpful for diagnosing.

**Comment by RichardLitt** [comment]
@nolanlawson It looks fine to me, too, which is what is confusing. What would you suggest for setting up live code to reproduce? The live code is here: https://github.com/BeagleLab/beagle/tree/feature/save-images but it is a bit of a hassle to get it running, as it is in a Chrome extension. I can walk you through it if you feel that would be the easiest way?

**Comment by nolanlawson** [comment]
Can you get the test to fail in any environment other than a Chrome extension? If not, then that may hint that the problem is related to the Chrome extension environment itself.

**Comment by RichardLitt** [comment]
Well, this seemed to work:

```
var PouchDB = require('pouchdb')
var db = new PouchDB('sandbox')

db.put({'_id': 'kitten'})

function saveSelection (documentId, selection) {
  console.log('Inside saveSelection')

  db.get('kitten').then(function (value) {
    console.log('value', value)

    /* Instantiate the object if it doesn't exist yet */
    value = value || {}
    value._id = 'kitten'

    /* Add in the selection to the selections array */
    value.selections = value.selections || []
    value.selections.push(selection)

    /* Get rid of prototypes so we can put this to the database */
    value = JSON.parse(JSON.stringify(value))

    console.log('value', value)
    return db.put(value)
  }).then(function (response) {
    console.log('response', response)

  }).catch(function (err) {
    console.log(err)
  })
}

saveSelection('kitten', {'tree': 'tree'})
```

:/ Maybe it's a Chrome problem? Why would that be an issue?

**Comment by nolanlawson** [comment]
I'm not sure what the issue was, but if it's working now, then I'll just close this issue. Let me know if you run into anything else!

**Comment by RichardLitt** [comment]
@nolanlawson It's still not working. I would keep this open in case anyone has any suggestions - while the code above works, that is in a normal environment, not in a Chrome Extension using browserify.

**Comment by nolanlawson** [comment]
I tried to reproduce your issue, but everything seems normal: http://bl.ocks.org/nolanlawson/36ece5ba0723f68117c4 Notice that the output is fine (unless you refresh, in which case there is a conflict, which is totally expected).

If you can provide a reproducible test case, then it would be easier to deduce the issue...

**Comment by nolanlawson** [comment]
Sorry, I didn't notice you already provided a live test case. So then follow-up question: is your code only failing as a Chrome extension?

**Comment by nolanlawson** [comment]
FWIW I tried to run your `beagle` project in my Chrome, but got the following error:

    Mixed Content: The page at 'https://github.com/BeagleLab/voyage' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://54.164.111.240:5984/test/?_nonce=1430020256853'. This request has been blocked; the content must be served over HTTPS.

Then I tried to change the CouchDB URL but ended up with the following error when running `gulp`:

    Error: Cannot find module 'beagle-style' from '~/workspace/beagle/js'

This is almost undoubtedly a Chrome extension issue. If you can step through line-by-line, you can probably find where it is failing.

TBH we haven't run the PouchDB test suite in a Chrome extension, because I wouldn't even know where to start. We did test it in a Chrome packaged app, though, and everything works fine except for map/reduce as described here: https://github.com/nolanlawson/pouchdb-chrome-app

**Comment by RichardLitt** [comment]
Thanks for going above and beyond, @nolanlawson. Can you explain what this conflict would look like: 

> Notice that the output is fine (unless you refresh, in which case there is a conflict, which is totally expected).

Would it throw an error in the console? 

My code is only failing in my Chrome extension. I plan to make a website version soon that isn't in the Chrome extension - I'll see if it fails there, too. 

I haven't seen that Mixed Content error before, weird. The `gulp` error is expected - those two modules need to be manually loaded. I'll change the workflow of the app so that that doesn't happen, it's too much of a unnecessary hurdle - so, thanks for that feedback. 

That's ok it hasn't been in run in a Chrome extension - maybe this is a good thing I can try and do. Thanks for that link. I'll keep an eye on it.

**Comment by RichardLitt** [comment]
I fixed that `gulp` error. Shouldn't be a problem anymore.

**Comment by nolanlawson** [comment]
Yes, the conflict would definitely cause an error you can `.catch()`. Our promises should resolve exactly once with an error or success; if they fail silently, we're doing something very wrong. :/

**Comment by nolanlawson** [comment]
`npm install && gulp` is still throwing the same error about `beagle-style`...

**Comment by RichardLitt** [comment]
Updated `shrinkwrap.json`. Should be good now. Learning experience, thanks a ton.

**Comment by nolanlawson** [comment]
I played around a bit but wasn't sure how to set a breakpoint on `db.put()` or reproduce the issue. (I'm not familiar with Chrome extensions). When I tried it out, the breakpoint just never got hit:

![screenshot 2015-04-27 08 16 26](https://cloud.githubusercontent.com/assets/283842/7347352/d7a5686e-ecb5-11e4-988f-9b23bfab8003.png)


In general my guess is this:

1) PouchDB is really promisey and callbackey, which means it's easy to silently swallow errors if an unexpected synchronous exception is thrown
2) Somewhere Chrome extensions are disallowing something (I dunno, maybe localStorage? window.navigator? window.something probably), and it throws a synchronous error which is getting lost

So you could probably figure out what's going on by clicking the "pause on exceptions button." Other than that, I would set a breakpoint on `db.put()` and just step through the code line-by-line to try to see where it's throwing the error.

In general, we probably need to figure out how to run the PouchDB test suite inside of a Chrome extension. Running it inside of a Chrome app taught us a lot (e.g. that localStorage access is denied).

**Comment by nolanlawson** [comment]
Another guess: if `db.get()` works but not `db.put()`, then maybe there's a manifest file where you have to declare that you want write access to IndexedDB?

**Comment by RichardLitt** [comment]
@nolanlawson Alright. I think I found a problem which I may have been conflating with this one. I'm having issues rendering highlights on multiple pages of PDFs when the other pages haven't been loaded yet - something particular to my extension - which makes it look like the highlights haven't been saved, when they probably have. I've logged that issue, here: https://github.com/BeagleLab/beagle-pdf/issues/4

What this means for this issue is that the selections _are_ actually being saved. The issue is that I am not getting the console log from inside the response for unknown reasons. However, this downgrades the seriousness of this issue considerably for the moment. I've opened a clone issue in my repository [here](https://github.com/BeagleLab/beagle/issues/159) to keep myself reminded of it, and I'll check back in as I refactor some more of the code to fix the highlight bug. 

Thanks so much for your help so far!

**Comment by nolanlawson** [comment]
Cool, if you figure it out, let us know. :) We definitely want PouchDB to work in Chrome extensions.

**Comment by daleharvey** [comment]
ok seems like we havent been able to reproduce, if its an actual issue in pouchdb then please reopen

**Comment by RichardLitt** [comment]
Will do! Thanks.
