### ISSUE TITLE
Saucelabs is faily

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#3974]
Seems like an issue on their end, all of a sudden getting a large but not total failure on saucelabs. Will ping someone

**Comment by daleharvey** [comment]
pinged some people I know from saucelabs, hoping its a known issue, gonna try upgrading sauce-connect-launcher to see if that makes a difference since we are on a fairly old version

**Comment by nolanlawson** [comment]
fixed by https://github.com/pouchdb/pouchdb/pull/3978

**Comment by daleharvey** [comment]
This isnt completely fixed, gonna keep it open till we can get back to around the stability we were having before

**Comment by daleharvey** [comment]
So I think between the sauceconnect upgrade and https://github.com/pouchdb/pouchdb/pull/3984 this should be back to being more stable
