### ISSUE TITLE
CouchDB Master browser tests failing

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#4575]
Again, it has been for a while, filing to take a look at

**Comment by kxepal** [comment]
Reason?

**Comment by daleharvey** [comment]
looks like a change in error code for the the first issue

**Comment by kxepal** [comment]
Yes, there were recent changes that doest that. See [COUCHDB-2534](https://issues.apache.org/jira/browse/COUCHDB-2534).

**Comment by willholley** [comment]
the breaking change is that CouchDB master rejects malformed design docs. The failing test ("Changes with invalid ddoc with no filter function") is explicitly using a malformed ddoc so fails to PUT the design document. 

Given that we already have a test to cover the same scenario with a valid ddoc ("Changes with `filters` key not present in ddoc"), I wonder what value the failing test provides? Ditto for "Changes with invalid ddoc with no map function".

@kxepal should this be noted as a breaking change in CouchDB 2.0 as ddocs which don't validate will not replicate from 1.X to 2.X?

**Comment by daleharvey** [comment]
If there is already a test for how we handle invalid ddocs then I am good removing the broken tests

**Comment by willholley** [comment]
I suggest we split out the test for "attempt to save invalid design doc" as we already have coverage for the invalid changes calls (missing view function, missing ddoc).

**Comment by kxepal** [comment]
@willholley Technically, that's not a breaking change, but a bug fix. But yes.

**Comment by daleharvey** [comment]
hrm, this is weird, seeing different errors locally than I do in travis even though I am running couchdb identically (via `docker run -d -p 3001:5984 klaemo/couchdb:2.0-dev --with-haproxy --with-admin-party-please -n 1`)

**Comment by daleharvey** [comment]
will fix my local bugs first then see whats up

**Comment by daleharvey** [comment]
@willholley Also @nolanlawson has added tests running against cloudant to the test suite, these and the couch 2.0 tests are the only failures, if there was anyone at cloudant that could take a look at why those tests are failing it would be awesome, ill be taking a look at the same time and happy to help out and hopefully we can get back to all green :)

**Comment by daleharvey** [comment]
https://travis-ci.org/pouchdb/pouchdb/builds/109605078 - https://travis-ci.org/pouchdb/pouchdb/jobs/109605109 is a link to the tests running against cloudant

**Comment by daleharvey** [comment]
Ok, so now running at 100% locally and not reproducing the perma fail that we are seeing on travis despite me running the exact same couchdb instance

**Comment by daleharvey** [comment]
So as far as I can tell, CI is actually running against couch 1.6.1 but with `isCouchMaster` being set to true

**Comment by daleharvey** [comment]
ok thats it

```
Setting environment variables from .travis.yml
$ export SAUCE_USERNAME=[secure]
$ export SAUCE_ACCESS_KEY=[secure]
$ export DASHBOARD_HOST=[secure]
$ export CLOUDANT_USERNAME=[secure]
$ export CLOUDANT_PASSWORD=[secure]
$ export COUCH_HOST=http://127.0.0.1:3001
$ export CLIENT=node
$ export SERVER=couchdb-master
...
before_install.3
$ export COUCH_HOST=http://127.0.0.1:3000
```

**Comment by daleharvey** [comment]
@garrensmith Can you ping us here when you have looked into having nmo configure CORS, I would prefer to avoid writing a cluster configurations for this just for pouchdb

Alternatively @klaemo is there any other way to configure the cluster built into the docker process?

**Comment by klaemo** [comment]
Maybe this comment (and the following ones) can help: https://github.com/klaemo/docker-couchdb/issues/42#issuecomment-169610897

I dunno

**Comment by garrensmith** [comment]
@klaemo I think @daleharvey has solved it to some degree. We just needed to run some curl commands to set the correct CORS config for the node.

**Comment by daleharvey** [comment]
Yup thanks for the help, so the next fail is the test

```
    it('Non-live changes filter, descending', function (done) {
      var docs1 = [
        {_id: '0', integer: 0},
        {_id: '1', integer: 1},
        {_id: '2', integer: 2},
        {_id: '3', integer: 3}
      ];
      var db = new PouchDB(dbs.name);
      db.bulkDocs({ docs: docs1 }, function () {
        db.changes({
          descending: true
        }).on('complete', function (allChanges) {
          db.changes({
            descending: true,
            filter: function (doc) {
              return doc.integer > 2;
            }
          }).on('complete', function (filteredChanges) {
            // Should get docs 2 and 3 if the filter
            // has been applied correctly.
            filteredChanges.results.length.should.equal(1);

            // FAILS ON THIS LINE
            filteredChanges.last_seq.should.deep.equal(allChanges.last_seq);
            done();
          }).on('error', done);
        }).on('error', done);
      });
});
```
(from https://github.com/pouchdb/pouchdb/blob/master/tests/integration/test.changes.js#L1891)

Is this an invalid assumption to make? Node tests seem to pass this fine but it may be a timing issue, and obviously it is passing fine on Couch 1.6.x. 

@rnewson / @kxepal any thoughts on this? Cheers

**Comment by kxepal** [comment]
@daleharvey When you got this failure? Filtered changes were indeed broken, but all fixed at today's morning (~12h ago).

**Comment by daleharvey** [comment]
Changed the title because its not due to cors, but still failing https://travis-ci.org/pouchdb/pouchdb/jobs/129194072

**Comment by daleharvey** [comment]
From @willholley 
> 
> So the errors I see are along the lines of:
> 
> 2016-06-06 10:46:26.810 [error] node1@127.0.0.1 <0.29647.2> Could not open file /usr/src/couchdb/dev/lib/node1/data/shards/00000000-1fffffff/testdb.1465209986.couch: no such file or directory
> 
> (more complete log at https://gist.github.com/willholley/d200157ccdd3bc30485dbf1d9b0b9eae)
> 
> It doesn't happen at a consistent point in the tests.
> 
> When I run against CouchDB master locally (rather than using the Docker image), I occasionally see this error as well, though the test suite passes ~80% of the time.

**Comment by garrensmith** [comment]
Not sure if this is 100% useful since Pouchdb tests are a lot more complicated. But I resolved this for pouchdb-find [here](https://github.com/nolanlawson/pouchdb-find/commit/a30d5bb8074a154d1d02c40ace9daa298a6b4a6c)

**Comment by willholley** [comment]
also, looking at my gist with fresh eyes, the error makes total sense given the order of requests logged. Maybe that's another avenue for investigation...

**Comment by willholley** [comment]
so the error is that CouchDB is returning a 500 instead of a 404 when we GET /testdb and it doesn't exist. I'll try and repro in a script and submit a bug report.

**Comment by daleharvey** [comment]
All green
