### ISSUE TITLE
destroyed event fired twice

### ISSUE THREAD

**Issue by cdaringe** [pouchdb/pouchdb#4922]
hi all!  i'm seeing the `destroyed` event fired twice [in a barebones example](https://github.com/cdaringe/pouchdb-double-destroy).

```js
'use strict';
const pdbs = require('spawn-pouchdb-server');
const PouchDB = require('pouchdb');
pdbs({
    backend: false, // e.g. memdown
    config: { file: false },
    log: { file: false },
    port: 8888,
    timeout: 10000, // in ms
    verbose: true
}, function (err, srv) {
    var count = 0;
    PouchDB.on('destroyed', () => {
        ++count;
        console.log('destroy count:', count);
    });
    const p = new PouchDB('http://localhost:8888/test-db');
    p.put({ _id: 'dummy-id' })
    .then(() => p.destroy())
    .then(() => {
        srv.kill();
    })
});
```

yields ==>

```
cdieringer@Snapper-osx:~/node/double-pouch-destroy$ node index.js
writing config file at /var/folders/s6/fzmmr2s11_92ft6bz5m3qhqr0000gn/T/tmp-24120ghYVmUm4leXR
starting pouchdb-server --config /var/folders/s6/fzmmr2s11_92ft6bz5m3qhqr0000gn/T/tmp-24120ghYVmUm4leXR --in-memory
destroy count: 1
destroy count: 2
```

I've tested with CouchDB as the backend and PouchDB server.  The GH repo posted above should be a real easy thing to clone and try yourself.  thanks!

**Comment by nolanlawson** [comment]
Yup, I can confirm. Also for the record, you don't need to `require('spawn-pouchdb-server')` to reproduce this.

**Comment by cdaringe** [comment]
i should have mentioned that the `created` event also gets fired a of couple times.  i did obverse variable counts of calls to the event handler depending on the run.

**Comment by cdaringe** [comment]
not sure how the pure http client works, but if it does local caching (e.g. has a local db, vs. purely connecting to the remote db), the local version and the remote DB would be instantiated in my example.  if you reproduced without any remote, however, then :(

**Comment by daleharvey** [comment]
So I can reproduce with a `http` example, however 
```
'use strict';

const PouchDB = require('pouchdb');
var count = 0;

//const p = new PouchDB('http://localhost:5984/test-db');
const p = new PouchDB('test-db');

PouchDB.on('destroyed', () => {
  ++count;
  console.log('destroy count:', count);
});

p.put({ _id: 'dummy-id' }).then(function(res) {
  return p.destroy();
}).then(function() {
  return new Promise(resolve => {
    setTimeout(resolve, 200);
  });
});
``` 
is failing complete, not even completing the `put` and no errors thrown, super weird

**Comment by daleharvey** [comment]
Ok got a failing test for it, pretty complicated but looking into it now

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/da1859e807378cb8488b189e7483ac364bb9d873, it wasnt complicated at all :)

**Comment by cdaringe** [comment]
yahoo! :)

On Wed, Jun 1, 2016 at 7:35 AM, Dale Harvey <notifications@github.com>
wrote:

> Closed #4922 <https://github.com/pouchdb/pouchdb/issues/4922>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pouchdb/pouchdb/issues/4922#event-678416995>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AA9O_VfIjoQ2G7HUxwfJ9qNNF1Il-Ac2ks5qHYq2gaJpZM4HgAKH>
> .
>



-- 
Chris Dieringer
p: (503)358-8577
e: cdieringer@mrn.org
w: http://cdaringe.com

**Comment by gkiko** [comment]
I checked PouchDB 6.2.0 on **iOS** 11.4, **Safari** 11.1.2, **Chrome** 68.0.3440.106 and **Firefox** 61.0.2. This bug is still there for all browsers except Firefox. I ran the code below on https://pouchdb.com.
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/2578308/44858885-48f48100-ac73-11e8-86e8-55200b0d5b9f.png">

Then, I checked PouchDB 7.0.0 running in my ionic app on **iOS** 11.4. This is what I got
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/2578308/44859137-d637d580-ac73-11e8-92cf-6a3a1c7b0fe4.png">
