### ISSUE TITLE
dist folder missing on bower

### ISSUE THREAD

**Issue by e111077** [pouchdb/pouchdb#6112]
### Issue
The `dist` folder is missing when installing via bower. All is fine on npm.

### Info
- Environment: browser
- Platform: web / bower
- Adapter: N/A
- Server: N/A

### Reproduce
1. `bower i pouchdb`
2. Inspect `bower_components/pouchdb`

**Comment by mkazlauskas** [comment]
6.1.0 is fine, the problem is with 6.1.1

**Comment by mrbfrank** [comment]
+1

@mkazlauskas in the mean time you can pin your version to 6.1.0 in your project bower.json:

{
  "dependencies": {
    "pouchdb": "6.1.0"
  }
}

**Comment by electronicmax** [comment]
+1, please fix; thanks

**Comment by daleharvey** [comment]
Weird I thought we stopped supporting bower a while ago, I do remember that there didnt seem to have been a github tag made when I did the release but `npm run release` seemed to all work fine.

@nolanlawson can I just comment out the lerna stuff out of https://github.com/pouchdb/pouchdb/blob/master/bin/release.sh#L26 and do a new `npm run release`?

**Comment by nolanlawson** [comment]
@daleharvey hm so the reason this happened is apparently because the git tag was set up incorrectly. since bower just uses git tags, this can be fixed by updating the git tag in GitHub. I don't think you need to go so far as to re-run the entire script.

**Comment by nolanlawson** [comment]
I fixed this manually. Not sure what went wrong with our scripts, but we'll have to check next time we do a `npm run release`. It's supposed to create an extra commit for bower, tag that with the build number, then push the tags to GitHub. somehow the `6.1.1` tag only pointed to 844406f2a4d30832efebbea4e59ccb18588d0deb.

`bower install` works for me now. For the record, we still support Bower but will probably drop it at some point because the extra steps are a headache, and unpkg.com provides nearly the same features.

**Comment by nolanlawson** [comment]
New git commit for `6.1.1`: 9a203270a3748c567d9c8c0e18558eb5c7230609

**Comment by DanailMinchev** [comment]
I've tested again: only `6.1.0` has a `/dist` folder, but `6.1.1` still missing it.

My environment:
```
$ bower -v
1.8.0
$ npm -v
4.0.3
$ node -v
v6.9.2
```

**Comment by nolanlawson** [comment]
I can't reproduce. When I do `bower install pouchdb` I get 6.1.1 with a `dist` folder. Maybe you need to clear out your bower_components and reinstall?
