### ISSUE TITLE
allDocs() issue since Chromium 68

### ISSUE THREAD

**Issue by adrienverge** [pouchdb/pouchdb#7441]
Hi,

I don't know if it's related to PouchDB or Chromium, but I'm posting it here in case others experience the same problem. I haven't found anything about it on the internets.

When doing a prefix search (using `\ufff0` in `allDocs()` as described in [documentation](https://pouchdb.com/api.html#prefix-search)), with IndexedDB back-end, no results are returned (while there should be). When replacing `\ufff0` with `zzzz`, it works (results like `prefix:ja83kn02` are returned).

```js
await db.allDocs({include_docs: true, startkey: 'prefix:', endkey: 'prefix:\ufff0'})
```

Tested with:
- PouchDB 6 and Chromium 67: it works
- PouchDB 7 and Chromium 67: it works
- PouchDB 6 and Chromium 68: it bugs ❌
- PouchDB 7 and Chromium 68: it bugs ❌
- PouchDB 6 and Chrome 68: it works

I tested other "unicode high values" such as `\u1111`, `\u8000` etc. It works fine until `\u7fff`, and starts bugging from `\u8000`.

It looks like a bug in Chromium, however I'm not sure. The following commit (between v67 and v68) might be related: https://chromium.googlesource.com/chromium/src/+/56b8dabc3fb627039d9babbaa4707e8b038db4bc%5E%21/

Any idea?

**Comment by adrienverge** [comment]
@stale this issue is not stale, please don't close it.

**Comment by ptitjes** [comment]
So I can confirm this is a bug on Chromium 69, by adding the following test case in `test.all_docs.js`.
```javascript
    it('#7441 prefix with \\uffff end_key', function () {
      var db = new PouchDB(dbs.name);
      var docs = [{_id: 'prefix:a', foo: 'a'}, {_id: 'prefix:z', foo: 'z'}];
      return db.bulkDocs(docs).then(function () {
        return db.allDocs({start_key: 'prefix:', end_key: 'prefix:\uffff'});
      }).then(function (result) {
        result.rows.should.have.length(2, 'Return all docs');
      });
    });
```

It boils down to the native `getAll(...)` of IndexedDB returning no results at [getAll.js#L5](https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-adapter-idb/src/getAll.js#L5). I verified that the provided `keyRange` indeed includes the `"prefix:z"` key, so it really seems to be a bug of the native `getAll`.

This issue may also be the root cause of #7507, as `getIndexes()` uses it:
```javascript
  db.allDocs({
    startkey: '_design/',
    endkey: '_design/\uffff',
    include_docs: true
  })
```

I don't know where to go from there. I can't find a related issue on Chromium's bug tracker and I can't tell if it seems to be fixed in Chromium 70 as the `pouchdb-find` tests pass on Chromium/Travis. Any advice @daleharvey, @garrensmith? Maybe @SCdF as this is IndexedDB related?

**Comment by adrienverge** [comment]
@Stale this issue is still not stale, please don't close it.

**Comment by adrienverge** [comment]
@Stale this issue is still not stale, please don't close it.

**Comment by karlwestin** [comment]
@adrienverge i understand this issue is really important to you, but i don't really understand what it is you're after from PouchDB?
From what i read, the investigation shows that this is a Chromium issue mostly?

**Comment by adrienverge** [comment]
Hi @karlwestin, what makes you say that it's a Chromium issue? (I've researched I couldn't find whether it's related to Chromium or PouchDB.)

I try to let this issue open, since the bug is present and other users could be looking for it.

**Comment by karlwestin** [comment]
This comment here seems to say it's a Chromium issue https://github.com/pouchdb/pouchdb/issues/7441#issuecomment-441391598

It also says this is fixed in Chromium 70, which really makes me wonder why this issue needs extra attention?

Issue search brings up closed issues as well ;)

**Comment by adrienverge** [comment]
I don't know about that comment, but the bug still happens with Chromium 71.0.3578.98 and PouchDB 7.0.0 (I've just tested). Also, downgrading from PouchDB 7 to version 6 solves the problem.

@karlwestin have you tried? Do you experience the bug?

**Comment by karlwestin** [comment]
Ok great! Then we know that the issue is still there for Chromium 71, great!

I haven't tried sorry, i'm just trying to get more information out of you since you have the reproduction available :)

Would you be interested in working on fixing the issue?

**Comment by adrienverge** [comment]
For sure! I'd be glad to find the cause and fix it, like I already did in this repo (for other issues).

But I've already spent much time on this, both on Chromium's commit history and issue list, and on PouchDB code. I coudn't explain the bug. Any help from anyone that contributed to the 6 → 7 change would be more valuable.

**Comment by karlwestin** [comment]
Awesome let's start investigating a little, then maybe someone more can help!

So here's a JSBin where i'm trying to use the test case from @ptitjes to reproduce this issue: https://jsbin.com/cumiluyema/1/edit?html,js,output

Unfortunately, this test passes on Chromium 75.0.3749.0 (the one i could download from https://download-chromium.appspot.com/) on a Mac

As a starting point, can you try running the JSBin on your versions and see what result you get?
It's possible that the test is not enough to find the bug, if so, do you have any ideas what needs to be added in order to write a more thorough test?

**Comment by adrienverge** [comment]
@karlwestin thanks for following this up.

The JSBin you talk about uses PouchDB 6, which doesn't have the bug:
```html
...
<script src="https://cdn.jsdelivr.net/pouchdb/latest/pouchdb.min.js"></script>
<h1>Chromium test case for <a href="https://github.com/pouchdb/pouchdb/issues/7441">PouchDB bug #7441</h1>
...
```

    curl -s https://cdn.jsdelivr.net/pouchdb/latest/pouchdb.min.js | head -1
    // PouchDB 6.2.0

**Comment by karlwestin** [comment]
Ha, sorry damn right!
This version uses PouchDB 7.0.0 https://jsbin.com/zuhidafije/1/edit?html,js,output

However it still passes in Chromium version 69.0.3497.0 for me
Does it pass or fail for you?

What exact Chromium versions are you using?

**Comment by adrienverge** [comment]
Thanks for the heads up. We performed various tests on [this JS Bin with PouchDB 7](https://jsbin.com/zuhidafije/1/edit?html,js,output) with my team:
- computer A with Fedora 29 / Chromium 71.0.3578.98: `Wrong number of docs retured: 0`
- computer A with Fedora 29 / Firefox 66.0: `test passed`
- computer B with Fedora 29 / Chromium 73.0.3683.75: `Wrong number of docs retured: 0`
- computer B with Fedora 29 / Chrome 73.0.3683.86: `test passed`
- computer C with Fedora 29 / Chromium 73.0.3683.75: `Wrong number of docs retured: 0`
- computer C with Fedora 29 / Vivaldi 2.3.1440.60 `test passed`
- computer D with Fedora 29 / Chromium 71.0.3578.98: `Wrong number of docs retured: 0`

So it seems to fail on all versions of Chromium, at least on Fedora.

**Comment by ptitjes** [comment]
@karlwestin, do you have any clue as to where the problem comes from ? I am also on Fedora 29 / Chromium 73.

**Comment by ZaWertun** [comment]
Fedora 30, Chrome 75.0.3770.100 - no bug spotted.

**Comment by flimzy** [comment]
It looks like `GetAll.js` already has a fall-back mode. Would it be possible to detect this case (broken browser + `start_key` or `end_key` with a high Unicode value), and fallback to the cursor-based approach?
